export const siteConfig = {
  name: "Liang Shi",
  title: "Full Stack Engineer",
  description: "Passionate and detail-oriented Full Stack Engineer with over 5 years of experience in developing scalable, high-performance web applications. Proficient in modern frontend and backend technologies, including Next.js, React, Python. Adept at building responsive user interfaces, implementing robust APIs, and optimizing applications for performance and security. Passionate about AI-driven solutions.",
  url: "https://example.com",
  ogImage: "https://example.com/og.jpg",
  links: {
    github: "https://github.com/Evan9450",
    linkedin: "https://www.linkedin.com/in/liang-shi-5691a419a/",
    email: "evan9450@gmail.com",
  },
  stats: {
    experience: "5+",
    projects: "20+",
    clients: "10+",
    technologies: "10+",
  },
  skills: [
    "JavaScript",
    "TypeScript",
    "Python",
    "React",
    "Next.js",
    "MUI",
    "Bootstrap",
    "Tailwind CSS",
    "Django",
    "Docker",
    "PostgreSQL",
    "MySQL",
    "DynamoDB",
    "AWS",
  ],
} as const; 